---
dist: bionic

git:
  quiet: true

language: php
php:
  - '7.3'
  - '7.4'

services:
  - mysql

before_install:
  - make database

before_script:
  - composer self-update

script:
  - make environment
  - composer install
  - composer style-check
  - composer security-check
  - make install
  - make test

after_failure:
  - make logs

