---
dist: bionic

git:
  quiet: true

language: php
php:
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly

services:
  - mysql

before_install:
  - make database

before_script:
  - composer self-update

script:
  - make environment
  - composer install
  - make phpcs
  - composer style-check
  - composer security-check
  - make install
  - make test

after_failure:
  - make logs

